FROM postgres
ENV POSTGRES_PASSWORD docker
ENV POSTGRES_DB MovieServer
COPY db_schema_content.sql /docker-entrypoint-initdb.d/
ENV POSTGRES_PASSWORD docker
ENV POSTGRES_DB dose
COPY db_schema_main.sql /docker-entrypoint-initdb.d/
